spring.application.name=flagdemo

spring.datasource.url=jdbc:sqlite::resource:static/DB/Flaggle.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite dialect from hibernate-community-dialects
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false