spring.application.name=flagdemo

# DataSource - SQLite
spring.datasource.url=jdbc:sqlite:DB/Flaggle.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=com.example.flagdemo.SQLiteDialect
spring.jpa.show-sql=true

# Thymeleaf settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false